language: python
python:
  - '3.7'
  - '3.8'
env:
  - DJANGO_VERSION=2.2.11
  - DJANGO_VERSION=2.2.12
install:
  - make deps
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install
script:
  - make lint
  - make ci_test
  - make docs
