# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Lint and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
        django-version: [2.2.11, 2.2.12]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies with ${{ matrix.django-version }}
      run: |
        python -m pip install --upgrade pip
        pip install -q mypy==0.770 flake8==3.7.9
        pip install -q Django==${{ matrix.django-version }}
        python setup.py -q install
      with:
        django.python-version: ${{ matrix.django-version }}
    - name: Lint with flake8 and mypy
      run: |
        make lint
    - name: Test with pytest
      run: |
        make ci_test
